server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.136.140
    username: ll
    password: 12345
    listener:
      type: simple
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
    virtual-host: /ll
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug