server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route #商品搜索路由
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route1 #商城主页路由1
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com,gmall.com
        - id: index-route2 #商城主页路由2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route #商品详情路由
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route #单点登录路由
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
          filters:
            - Auth=
auth:
  jwt:
    publicKeyPath: D:/zResources/rsa/rsa.pub # 公钥地址
    cookieName: GMALL-TOKEN