server:
  port: 18085
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  rabbitmq:
    host: 192.168.136.140
    virtual-host: /ll
    username: ll
    password: 12345
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
    publisher-confirm-type: correlated
    publisher-returns: true
  redis:
    host: 192.168.136.140
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.140:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增