server:
  port: 18082
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 192.168.136.140
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.140:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/ums/*.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
aliyun:
  sms: #阿里云短信服务自定义配置类
    signName: 你的短信签名
    templateCode: 你的短信模板
    codePrefix: ums:code
    keyId: 你的阿里云账户
    keySecret: 你的账户密码
